apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: staging-orderui-build
  name: staging-orderui-build
  namespace: nges-core-framework
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'staging-orderui:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'nginx:stable-alpine'
    type: Docker

