kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: order
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/LEADSNGFS/order'
    sourceSecret:
      name: github-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile
    type: JenkinsPipeline

